cards/urls.py
from django.conf.urls import patterns, url

from cards import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^type4/', include('type4.urls', namespace="type4")),
    url(r'^admin/', include(admin.site.urls)),
)

type4/urls.py
from django.conf.urls import patterns, url

from type4 import views, admin_views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.all_cards, name='all_cards'),
    url(r'^filter/$', views.filter, name='filter'),
    url(r'^changes/$', views.changes, name='changes'),
    url(r'^admin/add_cards/$', admin_views.add_cards, name='admin_add_cards'),
    url(r'^admin/update/$', admin_views.update, name='admin_update'),
)

cards/models.py
from django.db import models
import logging

logger = logging.getLogger(__name__)

class Card(models.Model):

	# fields
    name = models.CharField(max_length=100)
    isSorcery = models.BooleanField('is sorcery speed', default=False)
    
    # funcs
    def is_in_stack(self):
    	ordered_statuses = Status.objects.filter(
    		card_id = self.id
    	).order_by('timestamp')
    	current_status = ordered_statuses[ordered_statuses.count()-1]
    	logger.critical(current_status)
    	return current_status.is_in_stack()
    is_in_stack.boolean = True
    
    def __unicode__(self):
        return self.name

class Status(models.Model):
    
    # status enum
	IN_STACK = 1
	GOING_IN_STACK = 2
	REMOVED_FROM_STACK = 3
	REJECTED_FROM_STACK = 4
	STATUS_CHOICES = (
		(IN_STACK, 'Currently in stack'),
		(GOING_IN_STACK, 'Waiting to be added'),
		(REMOVED_FROM_STACK, 'Playtested and then removed'),
		(REJECTED_FROM_STACK, 'Do NOT intend to try'),
	)

	# fields
	card = models.ForeignKey(Card)
	status = models.IntegerField(
		choices=STATUS_CHOICES,
		default=IN_STACK)
	timestamp = models.DateTimeField('timestamp')
    
    # funcs
	def is_in_stack(self):
		return self.status == self.IN_STACK

	def __unicode__(self):
		str = ''
		if not self.is_in_stack():
			str = 'NOT '
		return (self.card.name
			+ ' is ' 
			+ str
			+ 'in the stack')

type4/models.py
from django.db import models
from django.utils import timezone

import logging
logger = logging.getLogger(__name__)

class Card(models.Model):

	# fields
	name = models.CharField(max_length=100)
	is_instant = models.BooleanField('is instant or has flash', default=False)
	is_wrath = models.BooleanField('is one-shot mass removal or bounce', default=False)
	is_burn = models.BooleanField('burns players', default=False)
	is_lifegain = models.BooleanField('gives life', default=False)
	is_creature_fat = models.BooleanField('permanent: creature with combined p/t >= 14', default=False)
	is_creature_threat = models.BooleanField('permanent: creature with power >= 4', default=False)
	is_creature = models.BooleanField('permanent: creature', default=False)
	is_artifact = models.BooleanField('permanent: artifact', default=False)
	is_enchantment = models.BooleanField('permanent: enchantment', default=False)
	is_counterspell = models.BooleanField('counters spells', default=False)
	is_masticore = models.BooleanField('masticore', default=False)
	is_draw = models.BooleanField('draws more than one card', default=False)
	is_removal_creature = models.BooleanField('kills: creatures', default=False)
	is_removal_artifact = models.BooleanField('kills: artifacts', default=False)
	is_removal_enchantment = models.BooleanField('kills: enchantments', default=False)
	is_removal_land = models.BooleanField('kills: land', default=False)	
    
    # for use only by admin site
	def current_status(self):
		recent_statuses = Status.objects.filter(
			card_id = self.id
		).order_by('-timestamp')
		if recent_statuses:
			return recent_statuses[0].status
		return None

	def __unicode__(self):
		return self.name

	@staticmethod
	def flags():
		return list(n for n in Card._meta.get_all_field_names() if n.startswith('is_'))

class StatusChoice():
	name = ''
	id = 0

class Status(models.Model):
    
    # status enum
	IN_STACK = 1
	GOING_IN_STACK = 2
	REMOVED_FROM_STACK = 3
	REJECTED_FROM_STACK = 4
	STATUS_CHOICES = (
		(IN_STACK, 'Currently in stack'),
		(GOING_IN_STACK, 'Waiting to be added'),
		(REMOVED_FROM_STACK, 'Playtested and then removed'),
		(REJECTED_FROM_STACK, 'Do NOT intend to try'),
	)

	# fields
	card = models.ForeignKey(Card)
	status = models.IntegerField(
		choices=STATUS_CHOICES,
		default=IN_STACK)
	timestamp = models.DateTimeField('timestamp')
    
    # funcs	
	def status_choices(self):
		choices = []
		for c in self.STATUS_CHOICES:
			s = StatusChoice()
			s.id = c[0]
			s.name = c[1]
			choices.append(s)
		return choices
    
	def is_in_stack(self):
		return self.status == self.IN_STACK

	def __unicode__(self):
		str = ''
		if not self.is_in_stack():
			str = 'NOT '
		return (self.card.name
			+ ' is ' 
			+ str
			+ 'in the stack')

type4/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget

class ChangesForm(forms.Form):
	YEAR_CHOICES = ['2014','2015']
	from_timestamp = forms.DateTimeField(
		widget=SelectDateWidget(years=YEAR_CHOICES))
	to_timestamp = forms.DateTimeField(
		widget=SelectDateWidget(years=YEAR_CHOICES))

cards/views.py
from django.http import HttpResponse
from django.shortcuts import render

from cards.models import Card

def index(request):
    all_cards = Card.objects.order_by('name')
    filtered_cards = list(c for c in all_cards if c.is_in_stack())
    context = {'filtered_cards': filtered_cards}
    return render(request, 'cards/index.html', context)   
    

type4/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import render
from type4.models import Card, Status
from type4.classes import CardWrapper
from type4.forms import ChangesForm

import logging
logger = logging.getLogger(__name__)

def extract_names(cards):
	return '|'.join(sorted(c.name for c in cards)) #change to sorted?

def index(request):
    all_cards = CardWrapper.get_cards()
    filtered_cards = list(c for c in all_cards if c.is_in_stack())
    card_names = extract_names(filtered_cards)
    context = {
    	'card_names': card_names,
    	'card_count': len(filtered_cards),
    	'show_art': 'false',
	}
    return render(request, 'type4/default.html', context)  

def __all_cards_context(wrappers):
	dict = CardWrapper.filter_cards_by_status(wrappers)    
	in_cards = dict[Status.IN_STACK]
	want_cards = dict[Status.GOING_IN_STACK]
	removed_cards = dict[Status.REMOVED_FROM_STACK]
	rejected_cards = dict[Status.REJECTED_FROM_STACK]
	context = {
		'show_art': 'false',
		'in_names': extract_names(in_cards),
		'want_names': extract_names(want_cards),
		'removed_names': extract_names(removed_cards),
		'rejected_names': extract_names(rejected_cards),
		'in_count': len(in_cards),
		'want_count': len(want_cards),
		'removed_count': len(removed_cards),
		'rejected_count': len(rejected_cards),
	}
	return context
	
def all_cards(request):
	wrappers = CardWrapper.get_cards()
	context = __all_cards_context(wrappers)
	return render(request, 'type4/all_cards.html', context)  

def filter(request):
	flag_set = Card.flags()
	filter_dict = {}
	for f in flag_set:
		if f in request.GET:
			s = request.GET[f]
			if s == 'True':
				filter_dict[f] = True
			if s == 'False':
				filter_dict[f] = False
	cards = Card.objects.filter(**filter_dict)
	ids = list(c.id for c in cards)
	wrappers = CardWrapper.get_cards_by_id(ids)
	context = __all_cards_context(wrappers)
	context['flag_set'] = flag_set
	return render(request, 'type4/filter.html', context)  
    
def changes(request):
	form = ChangesForm(request.GET)
	if form.is_valid(): # All validation rules pass
		cd = form.cleaned_data
		from_timestamp = cd['from_timestamp']
		to_timestamp = cd['to_timestamp']
		if to_timestamp <= from_timestamp:
			raise Exception('From must be before To')
		all_cards = CardWrapper.get_cards()
		cards_before = list(c for c in all_cards if c.was_in_stack(from_timestamp))
		cards_after = list(c for c in all_cards if c.was_in_stack(to_timestamp))
		cards_added = list(c for c in cards_after if c not in cards_before)
		cards_removed = list(c for c in cards_before if c not in cards_after)
		context = {
			'form': form,
			'added_names': extract_names(cards_added),
			'added_count': len(cards_added),
			'removed_names': extract_names(cards_removed),
			'removed_count': len(cards_removed),
			'show_art': 'true',
		}
		return render(request, 'type4/changes.html', context)
	return render(request, 'type4/changes.html', {
		'form': form,
	})

type4/templates/type4/_cardlist.html
<!-- partial -->

<h3 class="cardlist-title"> {{ title }} </h3>

{% if card_names %}
	<div class="cardlist" data-art="{{ show_art }}">
		<div class="data">
		{{ card_names }}
		</div>
		<button class="toggle">Toggle image view</button>
		<span> {{ card_count }} cards </span>
		<br /><br />
	</div>
{% else %}
	<div> No cards found :( </div>
{% endif %}

type4/templates/type4/_mastertoggle.html
<!-- partial -->

<button id="mastertoggle">Toggle all toggles</button>
<br />

<script type="text/javascript">		
		$(document).on("ready", function(){		
			$('#mastertoggle').on('click', function (){
				console.log('fuck');
				$('.toggle').trigger('click');
			});
		});		
</script>

type4/templates/type4/add_cards.html
<body>

<h1>Add cards</h1>
	
<form action="{% url 'type4:update' %}" method="post">
	{% csrf_token %}
	<label>Inclusion status:</label>
	<select name="status">
		{% for status_choice in status_set %}
		<option value="{{ status_choice.id }}">{{ status_choice.name }}</option>
		{% endfor %}
	</select>
	
	{% for flag in flag_set %}
	<br/>
	<label>{{flag}}</label>
	<select name="{{flag}}">
		<option value="None">-</option>
		<option value="True">True</option>
		<option value="False">False</option>
	</select>
	{% endfor %}
	
	<h3>Paste card names here</h3>
	<textarea name="card_names"></textarea>
	
	<br />
	<input type="submit" value="Submit" />
</form>
	
</body>

type4/templates/type4/admin_add_cards.html
<body>

<h1>Add cards</h1>
	
<form action="{% url 'type4:admin_update' %}" method="post">
	{% csrf_token %}
	<label>Inclusion status:</label>
	<select name="status">
		{% for status_choice in status_set %}
		<option value="{{ status_choice.id }}">{{ status_choice.name }}</option>
		{% endfor %}
	</select>
	
	{% for flag in flag_set %}
	<br/>
	<label>{{flag}}</label>
	<select name="{{flag}}">
		<option value="None">-</option>
		<option value="True">True</option>
		<option value="False">False</option>
	</select>
	{% endfor %}
	
	<h3>Paste card names here</h3>
	<textarea name="card_names"></textarea>
	
	<br />
	<input type="submit" value="Submit" />
</form>
	
</body>

type4/templates/type4/all_cards.html
{% extends "type4/base.html" %}

{% block subtitle %}
	 - Full List
{% endblock %}

{% block intro %}

<h4> Listed here is every card that's ever been included/rejected/considered </h4>

{% endblock %}

{% block content %}

{% include "type4/_mastertoggle.html" %}

{% include "type4/_cardlist.html" with title='Current list' card_names=in_names card_count=in_count %}

{% include "type4/_cardlist.html" with title='Cards I want to add' card_names=want_names card_count=want_count %}

{% include "type4/_cardlist.html" with title='Cards that have been cut' card_names=removed_names card_count=removed_count %}

{% include "type4/_cardlist.html" with title='Cards that would never work' card_names=rejected_names card_count=rejected_count %}

{% endblock %}

type4/templates/type4/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
    	{% block title %}Type 4{% endblock %}
    	{% block subtitle %}{% endblock %}
    </title>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	
    {% load staticfiles %}
    <link rel="icon" href="{% static 'type4/images/favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'type4/style.css' %}" />
    <script src="{% static 'type4/cardlist.js' %}"></script>
	
</head>

<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'type4:index' %}">Type 4</a>
			</div>

			<ul class="nav navbar-nav navbar-left">
				<li><a href="http://google.com">Blog</a></li>
				<li><a href="{% url 'type4:all_cards' %}">Full List</a></li>
				<li><a href="{% url 'type4:filter' %}">Categories</a></li>
				<li><a href="{% url 'type4:changes' %}">Changes</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a href="/admin/">Admin</a></li>
			</ul>
		</div><!-- /.container-fluid -->
	</nav>

    <div class="container">
		{% block intro %}{% endblock %}
		<hr>
        {% block content %}{% endblock %}
    </div>
    
    <script type="text/javascript">		
			$(document).on("ready", init_cardlist);		
	</script>
	<script src="{% static 'type4/gatherer_helper.js' %}"></script>
	<script src="{% static 'type4/autocard.js' %}"></script>
</body>
</html>

type4/templates/type4/changes.html
{% extends "type4/base.html" %}

{% block subtitle %}
	 - Changes
{% endblock %}

{% block intro %}

<h1> View changes </h1>

<form action="{% url 'type4:changes' %}" method="GET">
	{{ form.as_p }}
	<input type="submit" value="Refresh" />
</form>

{% endblock %}

{% block content %}

{% include "type4/_cardlist.html" with title='Added' card_names=added_names card_count=added_count %}

{% include "type4/_cardlist.html" with title='Removed' card_names=removed_names card_count=removed_count %}
	
{% endblock %}

type4/templates/type4/default.html
{% extends "type4/base.html" %}

{% block intro %}

<h3> Welcome to my website blah blah blah </h3>

{% endblock %}

{% block content %}

{% include "type4/_cardlist.html" with title='Card list' %}
	
{% endblock %}

type4/templates/type4/filter.html
{% extends "type4/all_cards.html" %}

{% block subtitle %}
	 - Filter
{% endblock %}

{% block intro %}

<h1> Filter by Category </h1>

<form action="{% url 'type4:filter' %}" method="get">
	
	{% for flag in flag_set %}
	<br/>
	<label>{{flag}}</label>
	<select name="{{flag}}">
		<option value="None">-</option>
		<option value="True">True</option>
		<option value="False">False</option>
	</select>
	{% endfor %}
	
	<br />
	<input type="submit" value="Submit" />
	
</form>

{% endblock %}